platform :osx, '11.0'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_sync
  # 由 flutter 工具生成
end

require File.expand_path(
    File.join('..', 'flutter', 'flutter_macos_podfile_helper'))

target 'Runner' do
  use_frameworks!

  flutter_sync
  flutter_install_macos_pods(File.dirname(__FILE__))

  # TVS 专用 pod（macOS 版同样内嵌 Node 引擎与 FFmpeg 桥）。
  pod 'NodeMobile', :path => '../nodejs_mobile/macos'
  pod 'YlFFmpegBridge', :path => '../packages/yl_player/darwin/ffmpeg_bridge'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end
