// CatVod Spider 路由注册表（还原自 kstore_index.js / catpaw_index.js）
// 供二次开发与调试参考；线上实际路由以 bundle 为准。
'use strict';

const KSTORE_ROUTES = [
  ['GET', '/diy/emby/servers'],
  ['POST', '/init'],
  ['POST', '/support'],
  ['POST', '/home'],
  ['POST', '/homeVod'],
  ['POST', '/homeVideo'],
  ['POST', '/category'],
  ['POST', '/detail'],
  ['POST', '/play'],
  ['POST', '/search'],
  ['GET', '/test'],
  ['GET', '/lrcproxy/:token'],
  ['GET', '/proxy/:provider/:sessionId'],
  ['GET', '/proxy/*'],
  ['GET', '/danmusearch'],
  ['GET', '/danmusearch/api/search'],
  ['GET', '/danmusearch/api/episodes'],
  ['GET', '/danmusearch/api/history'],
  ['GET', '/danmuput'],
  ['GET', '/danmu/auto-push'],
  ['GET', '/danmu/auto'],
  ['GET', '/danmu/manual'],
  ['GET', '/danmu'],
  ['GET', '/imageProxy'],
  ['GET', '/proxy/hls/*'],
  ['GET', '/website'],
  ['GET', '/website/api/config/qr'],
  ['GET', '/website/api/status'],
  ['GET', '/website/api/remote-wex'],
  ['GET', '/website/api/credentials'],
  ['GET', '/website/api/sites'],
  ['PUT', '/website/api/sites'],
  ['DELETE', '/website/api/sites'],
  ['GET', '/website/api/livetovod/url'],
  ['PUT', '/website/api/livetovod/url'],
  ['POST', '/website/api/login/start'],
  ['POST', '/website/api/login/poll'],
  ['POST', '/website/api/login/cancel'],
  ['PUT', '/website/api/credential/:provider/:field'],
  ['DELETE', '/website/api/credential/:provider/:field'],
];

const CATPAW_ROUTES = [
  ['GET', '/qrcode'],
  ['POST', '/check-status'],
  ['POST', '/cookie'],
  ['GET', '/cookie'],
  ['PUT', '/cookie'],
  ['GET', '/urls'],
  ['PUT', '/urls'],
  ['DELETE', '/urls'],
  ['POST', '/init'],
  ['POST', '/home'],
  ['POST', '/category'],
  ['POST', '/detail'],
  ['POST', '/play'],
  ['POST', '/search'],
  ['GET', '/test'],
  ['GET', '/proxy/:site/:what/:flag/:shareId/:fileId/:end'],
  ['GET', '/proxy/:img'],
  ['GET', '/config'],
  ['PUT', '/config'],
  ['DELETE', '/config'],
  ['GET', '/proxy/dash/:token/:quality/manifest.mpd'],
  ['GET', '/proxy/dash/:token/:quality/:track.m4s'],
  ['POST', '/support'],
  ['GET', '/sources'],
  ['POST', '/sources'],
  ['DELETE', '/sources/:index'],
  ['POST', '/homeVod'],
  ['GET', '/setting'],
  ['POST', '/verify'],
  ['PUT', '/setting'],
  ['DELETE', '/setting'],
  ['GET', '/image'],
  ['POST', '/server/:serverId/init'],
  ['POST', '/server/:serverId/home'],
  ['POST', '/server/:serverId/category'],
  ['POST', '/server/:serverId/detail'],
  ['POST', '/server/:serverId/play'],
  ['POST', '/server/:serverId/search'],
  ['GET', '/proxy/:id/:file'],
  ['GET', '/index/status'],
];

// 网盘 Provider 列表（14 个）
const PAN_PROVIDERS = [
  'y115', 'tianyi', 'new139', 'quark', 'uc', 'baidu',
  'pan123', 'guangya', 'guangyazhenying', 'woniu4k',
  'xunlei', 'bilibili_all', 'emby', 'pikpak', 'ali',
];

// 弹幕源
const DANMU_SOURCES = ['tencent', 'iqiyi', 'mgtv', 'rrsp'];

module.exports = { KSTORE_ROUTES, CATPAW_ROUTES, PAN_PROVIDERS, DANMU_SOURCES };